### ISSUE TITLE
[Error] Need config in utils package

### ISSUE THREAD

**Issue by TaoZex** [xuyimin0926/U-WADN#1]
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from net.model import AirNet
  File "/home/chenby/pre_module/WADN/U-WADN-main/net/model.py", line 5, in <module>
    from net.slimmable_op import SlimmableConv2d
  File "/home/chenby/pre_module/WADN/U-WADN-main/net/slimmable_op.py", line 4, in <module>
    from utils.config import FLAGS
ModuleNotFoundError: No module named 'utils.config'
```
This error was encountered while executing the code. It appears that there is no config file under the utils package.

**Comment by xuyimin0926** [comment]
Hi,

Thanks for your questions. I find that I forget to change the package name from 'slimmable_op' to 'wac_op', together with the class name in the model.py. You can change yourself, and I will upload a new version shortly afterwards.

Thanks.

**Comment by TaoZex** [comment]
> Hi,
> 
> Thanks for your questions. I find that I forget to change the package name from 'slimmable_op' to 'wac_op', together with the class name in the model.py. You can change yourself, and I will upload a new version shortly afterwards.
> 
> Thanks.

Thanks for your reply, which is very helpful to me.

**Comment by xuyimin0926** [comment]
My pleasure.
